### ISSUE TITLE
Assignment 1: Ready for grading

### ISSUE THREAD

**Issue by reed-cj** [SES-5215-F2020/creed1-quant#1]
I spent most of my time with this assignment working on a dataset that looks at either blocks or places in Minnesota and assesses median rent and owner costs in non-mortgage housing units, median income, housing structure type, and ethnicity, with the goal of identifying race-based rent and lot-rent disparities in MN mobile home parks. I had to change course to avoid risking a late submission, but I am hopeful that I'll get the chance to complete that dataset before beginning Assignment 2

**Comment by saratepfer** [comment]
Thank you, Chad. Nice work. A few comments, below.

**Comments on Content**
Based on the definitions [here](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMSDataDict13.txt), I believe BLD and ACR are categorical variables. You could transform BLD to a continuous variable using mutate and case_when, but as it currently exists in your dataset, it is categorical.

It looks like you are pulling more variables than are listed in lines 15-26. For example, your table shows that GRPIP is pulled, but it is not referenced in lines 15-26.

Your dataset is currently pretty big, but I think with a few filters to eliminate NAs (for example, all of the "b"s in Access), it will probably get a little more manageable. I recommend filtering your data to remove the NAs.
