### ISSUE TITLE
assignment 3 submission

### ISSUE THREAD

**Issue by reed-cj** [SES-5215-F2020/creed1-quant#3]
[Here](https://ses-5215-f2020.github.io/creed1-quant/[quant]assignment3) is the link to my submission for Assignment 3.

**Comment by saratepfer** [comment]
Nice job on this! Please see a few comments below.

- I wouldn't say the correlations are negligible. I would say they are weak, as you have.
- It would be great to add some interpretations of the Tukey HSD tests you have run. 
- It would be great to add some interpretations of the expected v. observed tables you have included for your chi square tests.
