### ISSUE TITLE
Assignment 4 Submission

### ISSUE THREAD

**Issue by reed-cj** [SES-5215-F2020/creed1-quant#4]
Link [here](https://ses-5215-f2020.github.io/creed1-quant/[quant]assignment4)

**Comment by saratepfer** [comment]
- line 17: replace {r} with {r, messages = FALSE} to prevent R from printing unnecessary messages in your knitted html file.
- It would be great if you included at least four independent variables in your model. You currently have three.
- I think you should be doing a logistic regression for your analysis. Your dependent variable is not numerical, it is categorical. Please schedule office hours to discuss.
